# file: .github/workflows/ci.yml
name: ci
on:
  push:
  pull_request:

permissions:
  contents: write  # allow the workflow to push auto-fixes

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: src
    steps:
      - uses: actions/checkout@v4
        with:
          # so we can push back to the same branch
          persist-credentials: true
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -U pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Ruff (format + fix)
        run: |
          . .venv/bin/activate
          ruff format
          ruff check src tests --fix --output-format=github

      - name: Commit auto-fixes (if any)
        run: |
          if ! git diff --quiet; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(ci): apply ruff auto-fixes"
            git push
          fi

      - name: Pytest
        run: |
          . .venv/bin/activate
          pytest -q
